#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os;
import sys;
import time;

print sys.argv[1] + " transform start "
start =time.clock()
with open(sys.argv[1]+'.tmp','w') as tmp:
    with open(sys.argv[1], 'r') as f:
        num = 0;
        for line in f:
            num += 1
            letter = []
            isstart = 0
            for i in range(len(line)):
                if line[i] == '\'' and isstart == 0:
                    letter.append(line[i])
                    isstart = 1
                    continue
                if line[i] == ',' and isstart == 0:
                    letter.append('\x01')
                    continue
                if line[i] == '\'' and isstart == 1:
                    letter.append(line[i])
                    isstart = 0
                    continue
                letter.append(line[i])
            tmp.write(''.join(letter))
end = time.clock()
print('Running time: %s Seconds'%(end-start))
