server:
  port: 18082

spring:
  application:
    name: edata-quartz  #全部小写

#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    com.efun.edata: DEBUG
    com.github.dexecutor: DEGUG
#####################################################################################################

