server:
  port: 18081

spring:
  application:
    name: edata-dexecutor  #全部小写

#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    com.efun.edata: DEBUG
    com.github.dexecutor: DEGUG
#####################################################################################################

#####################################################################################################
# 集成actuator管理
management:
  endpoints:
    web:
      base-path: /management
      path-mapping:
        health: health
#####################################################################################################
