version: '2'
services:
  uhdp-ambari:
    image: ubuntu/base:1.0
    hostname: uhdp-ambari
    container_name: uhdp-ambari
    dns: "114.114.114.114"
    volumes:
      - jdk:/usr/java/default
      - /opt/hdp/repo-ubuntu/:/var/www/html/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/bin/monit -I"
  uhdp-m1:
    image: ubuntu/base:1.0
    hostname: uhdp-m1
    container_name: uhdp-m1
    dns: "114.114.114.114"
    volumes:
      - jdk:/usr/java/default
      - /opt/hdp/data/um1/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/bin/monit -I"
  uhdp-s1:
    image: ubuntu/base:1.0
    hostname: uhdp-s1
    container_name: uhdp-s1
    dns: "114.114.114.114"
    volumes:
      - jdk:/usr/java/default
      - /opt/hdp/data/us1/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/bin/monit -I"
  uhdp-s2:
    image: ubuntu/base:1.0
    hostname: uhdp-s2
    container_name: uhdp-s2
    dns: "114.114.114.114"
    volumes:
      - jdk:/usr/java/default
      - /opt/hdp/data/us2/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/bin/monit -I"
  uhdp-s3:
    image: ubuntu/base:1.0
    hostname: uhdp-s3
    container_name: uhdp-s3
    dns: "114.114.114.114"
    volumes:
      - jdk:/usr/java/default
      - /opt/hdp/data/us3/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/bin/monit -I"

networks:
  default:
    external:
      name: hdp.net


volumes:
  jdk:
    external:
      name: jdk
