version: '2'
services:
  ubuntu-base:
    image: ubuntu:14.04
    hostname: ubuntu-base
    container_name: ubuntu-base
    dns: "114.114.114.114"
    volumes:
      - jdk:/usr/java/default
      - /opt/hdp/repo-ubuntu/:/var/www/html/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "ping localhost"

networks:
  default:
    external:
      name: hdp.net


volumes:
  jdk:
    external:
      name: jdk
