version: '2'
services:
  cdh-cm:
    image: centos/base:1.0
    hostname: cdh-cm
    container_name: cdh-cm
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/repo-centos/:/var/www/html/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"
  cdh-m1:
    image: centos/base:1.0
    hostname: cdh-m1
    container_name: cdh-m1
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/data/cm1/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"
  cdh-s1:
    image: centos/base:1.0
    hostname: cdh-s1
    container_name: cdh-s1
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/data/cs1/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"
  cdh-s2:
    image: centos/base:1.0
    hostname: cdh-s2
    container_name: cdh-s2
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/data/cs2/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"
  cdh-s3:
    image: centos/base:1.0
    hostname: cdh-s3
    container_name: cdh-s3
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/data/cs3/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"

networks:
  default:
    external:
      name: hdp.net


volumes:
  jdk:
    external:
      name: jdk
