version: '2'
services:
  cmgr-w1:
    image: centos/base:1.0
    hostname: cmgr-w1
    container_name: cmgr-w1
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/repo-centos/:/var/www/html/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"
  chdp-m1:
    image: centos/base:1.0
    hostname: chdp-m1
    container_name: chdp-m1
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/data/cm1/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"
  chdp-s1:
    image: centos/base:1.0
    hostname: chdp-s1
    container_name: chdp-s1
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/data/cs1/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"
  chdp-s2:
    image: centos/base:1.0
    hostname: chdp-s2
    container_name: chdp-s2
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/data/cs2/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"
  chdp-s3:
    image: centos/base:1.0
    hostname: chdp-s3
    container_name: chdp-s3
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/data/cs3/:/data/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"

networks:
  default:
    external:
      name: hdp_net


volumes:
  jdk:
    external:
      name: jdk
