version: '2'
services:
  centos-base:
    image: centos
    hostname: centos-base
    container_name: centos-base
    dns: "114.114.114.114"
    privileged: true
    volumes:
      - jdk:/usr/java/default
      - /opt/cdh/repo-centos/:/var/www/html/
    env_file:
      - container.env
    cap_add:
      - ALL
    command: "/usr/sbin/init"

networks:
  default:
    external:
      name: hdp.net


volumes:
  jdk:
    external:
      name: jdk
